# Generated by Django 5.1.7 on 2025-03-11 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="matiere",
            name="classe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matieres",
                to="data.classe",
            ),
        ),
        migrations.AddField(
            model_name="matiere",
            name="enseignant",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"user_type": "teacher"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matieres_enseignees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="matiere",
            name="semestre",
            field=models.IntegerField(
                choices=[
                    (1, "Semestre 1"),
                    (2, "Semestre 2"),
                    (3, "Semestre 3"),
                    (4, "Semestre 4"),
                ],
                default=1,
            ),
            preserve_default=False,
        ),
    ]
