# Generated by Django 5.1.6 on 2025-03-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_matiere_classe_matiere_enseignant_matiere_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='n_appogie',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
